import type { LocationArea } from '@/marketing/content/locations/types';

const CORE_SERVICE_SLUGS = [
  'community',
  'mentoring',
  'sen',
  'routine',
  'goals',
  'sports-support-programme',
] as const;

function areaFaq(placeName: string, keyAreaSample: string): LocationArea['faq'] {
  return [
    {
      q: `Do you provide chaperone services in ${placeName}?`,
      a: `Yes. CAMS services delivers chaperone services, child transport and mentoring across ${placeName} for local authorities, schools, foster agencies and families. Contact us to discuss availability in ${keyAreaSample} and surrounding neighbourhoods.`,
    },
    {
      q: `Which neighbourhoods in ${placeName} do you cover?`,
      a: `We plan journeys across the borough or town based on referrer need, including school runs, contact centre transport, foster moves and community access. Share postcodes when you refer so we can confirm routing and practitioner cover.`,
    },
    {
      q: `How do schools and local authorities refer in ${placeName}?`,
      a: `Use our online referral form or contact page. We respond within one working day with feasibility, safeguarding questions and recommended next steps.`,
    },
  ];
}

export const LOCATION_AREAS: readonly LocationArea[] = [
  {
    slug: 'ealing',
    name: 'Ealing',
    councilType: 'outer-london-borough',
    councilTypeLabel: 'Outer London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Ealing', 'Acton', 'Southall', 'Greenford', 'Hanwell', 'Perivale'],
    notes: 'CAMS services HQ is in Greenford, Ealing, our anchor borough for West London chaperone and transport cover.',
    borderingSlugs: ['hillingdon', 'hounslow', 'brent', 'harrow', 'hammersmith-and-fulham'],
    isHeadquarters: true,
    focusKeyword: 'chaperone services Ealing',
    metaTitle: 'Chaperone services Ealing | Child transport Greenford & West London',
    metaDescription:
      'Chaperone services and child transport in Ealing, Acton, Southall, Greenford and Hanwell. CAMS services Ltd, HQ in Greenford. DBS-checked practitioners for schools and local authorities.',
    heroDescription:
      'Chaperone services, school transport and mentoring from our Greenford base across Ealing, Acton, Southall, Hanwell and Perivale.',
    paragraphs: [
      'CAMS services is headquartered in Greenford, Ealing. Commissioners and families across the borough benefit from short routing times, familiar practitioners and consistent cover for contact centre journeys, SEMH-friendly school runs and foster placement transport.',
      'Ealing is one of West London’s most diverse boroughs. We work with schools, nurseries, IFAs and children’s services teams who need reliable chaperone service cover when relationships are high-conflict, when SEND transport plans require trauma-informed staff, or when a young person needs the same escort each week.',
      'Neighbourhoods we plan for regularly include Acton, Southall, Hanwell, Perivale and Northolt. If your case involves handovers near busy transport hubs or tight contact centre slots, include court or contact plan times in your referral so we can prioritise feasibility.',
    ],
    faq: areaFaq('Ealing', 'Greenford'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'harrow',
    name: 'Harrow',
    councilType: 'outer-london-borough',
    councilTypeLabel: 'Outer London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Harrow', 'Wealdstone', 'Pinner', 'Stanmore', 'Kenton'],
    notes: 'Borders Brent, Barnet and Hillingdon, with strong school and family referral routes from North West London.',
    borderingSlugs: ['brent', 'barnet', 'hillingdon', 'ealing'],
    focusKeyword: 'chaperone services Harrow',
    metaTitle: 'Chaperone services Harrow | Child transport Pinner & Stanmore',
    metaDescription:
      'Chaperone services and child transport in Harrow, Wealdstone, Pinner, Stanmore and Kenton. Safeguarding-led cover for schools, foster agencies and local authorities.',
    heroDescription:
      'Chaperone services and mentoring across Harrow, Wealdstone, Pinner, Stanmore and Kenton with practitioners who understand North West London travel patterns.',
    paragraphs: [
      'Harrow combines dense town centres with quieter residential streets towards Pinner and Stanmore. CAMS services plans chaperone service routes that respect school bell times, contact centre windows and placement geography across the borough.',
      'Referrers in Harrow often need joined-up transport when a young person moves between home, school and supervised contact. We document factual journey summaries for professionals and keep the same practitioner where consistency supports safeguarding.',
      'We also cover Kenton and Wealdstone with links into neighbouring Brent and Barnet when cases cross borough boundaries. Share full postcodes at referral so handovers stay unambiguous.',
    ],
    faq: areaFaq('Harrow', 'Pinner'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'brent',
    name: 'Brent',
    councilType: 'outer-london-borough',
    councilTypeLabel: 'Outer London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Wembley', 'Willesden', 'Kingsbury', 'Harlesden', 'Kilburn'],
    notes: 'Large, diverse population; borders Ealing, Harrow and Barnet.',
    borderingSlugs: ['ealing', 'harrow', 'barnet'],
    focusKeyword: 'chaperone services Brent',
    metaTitle: 'Chaperone services Brent | Child transport Wembley & Willesden',
    metaDescription:
      'Chaperone services in Brent: Wembley, Willesden, Kingsbury, Harlesden and Kilburn. Child transport and mentoring for schools and local authorities.',
    heroDescription:
      'Chaperone services and child transport across Brent, including Wembley, Willesden, Kingsbury, Harlesden and Kilburn.',
    paragraphs: [
      'Brent’s size and diversity mean transport plans must be precise: authorised recipients, prohibited contact persons and communication needs should be clear before the first journey. CAMS services provides chaperone service cover that local authorities and schools can commission with confidence.',
      'From event-day congestion near Wembley to school runs in Willesden and Kingsbury, we risk-assess routes and match practitioners with the right experience for SEMH, SEND or high-conflict contact.',
      'Brent cases often sit next to Ealing, Harrow or Barnet placements. Tell us if journeys cross borough lines so we can align timing with neighbouring teams.',
    ],
    faq: areaFaq('Brent', 'Wembley'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'hillingdon',
    name: 'Hillingdon',
    councilType: 'outer-london-borough',
    councilTypeLabel: 'Outer London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Uxbridge', 'Hayes', 'Ruislip', 'Northwood', 'West Drayton'],
    notes: 'Largest London borough by area; near Heathrow with complex travel patterns.',
    borderingSlugs: ['ealing', 'harrow', 'hounslow', 'richmond-upon-thames', 'hammersmith-and-fulham', 'slough'],
    focusKeyword: 'chaperone services Hillingdon',
    metaTitle: 'Chaperone services Hillingdon | Child transport Uxbridge & Hayes',
    metaDescription:
      'Chaperone services in Hillingdon: Uxbridge, Hayes, Ruislip, Northwood and West Drayton. School transport and contact centre cover near Heathrow and West London.',
    heroDescription:
      'Chaperone services across Hillingdon, from Uxbridge and Hayes to Ruislip, Northwood and West Drayton.',
    paragraphs: [
      'Hillingdon is London’s largest borough by area. Long cross-borough journeys and airport-corridor traffic demand realistic scheduling. CAMS services plans chaperone and child transport with buffer time, clear escalation routes and practitioner briefings that match each young person’s plan.',
      'Schools and IFAs in Hayes, West Drayton and Uxbridge commission us for SEMH school transport, placement moves and supervised contact when neutral handovers matter.',
      'Our Greenford HQ sits on the Hillingdon border, so West Drayton and Hayes routes are a natural fit. Include placement addresses and bell times when you refer.',
    ],
    faq: areaFaq('Hillingdon', 'Uxbridge'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'barnet',
    name: 'Barnet',
    councilType: 'outer-london-borough',
    councilTypeLabel: 'Outer London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Barnet', 'Finchley', 'Edgware', 'Mill Hill', 'Golders Green'],
    notes: 'Large family population with many schools, with strong demand for school transport and mentoring.',
    borderingSlugs: ['harrow', 'brent', 'enfield', 'hertsmere'],
    focusKeyword: 'chaperone services Barnet',
    metaTitle: 'Chaperone services Barnet | Child transport Finchley & Edgware',
    metaDescription:
      'Chaperone services in Barnet: Finchley, Edgware, Mill Hill and Golders Green. School transport, mentoring and family support for North London referrers.',
    heroDescription:
      'Chaperone services, school transport support and mentoring across Barnet, Finchley, Edgware, Mill Hill and Golders Green.',
    paragraphs: [
      'Barnet has one of North London’s highest concentrations of schools and family placements. CAMS services supports commissioners who need chaperone service hours for school attendance, contact transport or mentoring when behaviour and engagement need consistent adults.',
      'Finchley, Edgware and Mill Hill present different traffic and safeguarding contexts. We match practitioners to the case and keep referrers updated with factual session or journey notes where commissioned.',
      'Cross-border work with Harrow and Brent is common. Share court orders, PEP priorities and contact schedules at referral so transport and mentoring align with the wider plan.',
    ],
    faq: areaFaq('Barnet', 'Finchley'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'hounslow',
    name: 'Hounslow',
    councilType: 'outer-london-borough',
    councilTypeLabel: 'Outer London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Hounslow', 'Brentford', 'Chiswick', 'Feltham', 'Isleworth'],
    notes: 'Near Heathrow; strong transport links and varied referral types.',
    borderingSlugs: ['ealing', 'hillingdon', 'richmond-upon-thames', 'hammersmith-and-fulham'],
    focusKeyword: 'chaperone services Hounslow',
    metaTitle: 'Chaperone services Hounslow | Child transport Feltham & Brentford',
    metaDescription:
      'Chaperone services in Hounslow: Brentford, Chiswick, Feltham and Isleworth. Child transport and contact centre cover near Heathrow and West London.',
    heroDescription:
      'Chaperone services and child transport across Hounslow, Brentford, Chiswick, Feltham and Isleworth.',
    paragraphs: [
      'Hounslow’s proximity to Heathrow and major roads means chaperone service planning must account for delays, parking restrictions and sudden schedule changes. CAMS services provides dependable cover for contact centres, schools and foster networks across Feltham, Isleworth and Brentford.',
      'Chiswick and Brentford referrals often involve tight handover windows or shared care arrangements. We use neutral, factual documentation and escalate through agreed safeguarding routes when incidents occur.',
      'Hounslow borders Ealing and Hillingdon. Our Greenford team regularly serves West London corridors. Include authorised drop-off recipients and any non-molestation orders affecting travel.',
    ],
    faq: areaFaq('Hounslow', 'Feltham'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'watford',
    name: 'Watford',
    councilType: 'unitary-borough',
    councilTypeLabel: 'Hertfordshire (borough)',
    region: 'Hertfordshire',
    regionSlug: 'hertfordshire',
    keyAreas: ['Watford', 'Cassiobury', 'Nascot', 'Garston', 'Oxhey'],
    notes: 'Not a London borough. Hertfordshire town with strong links to West London commissioning routes.',
    borderingSlugs: ['harrow', 'ealing', 'hertsmere'],
    focusKeyword: 'chaperone services Watford',
    metaTitle: 'Chaperone services Watford | Child transport Hertfordshire',
    metaDescription:
      'Chaperone services in Watford and West Hertfordshire. Child transport, school runs and mentoring for families, schools and agencies linked to West London.',
    heroDescription:
      'Chaperone services and child transport in Watford and surrounding Hertfordshire neighbourhoods, with links into West London placement routes.',
    paragraphs: [
      'Watford sits in Hertfordshire but many placements and schools connect to West London networks. CAMS services covers Watford for chaperone services, school transport support and mentoring when commissioners need Hertfordshire delivery with London-grade safeguarding standards.',
      'Agencies in Garston, Oxhey and central Watford refer us for contact transport, foster moves and SEMH-friendly school runs. Share whether journeys terminate in London boroughs so we can plan cross-border timing.',
      'Our Greenford HQ is a short route from Watford. That helps with practitioner consistency and rapid feasibility checks for new referrals.',
    ],
    faq: areaFaq('Watford', 'central Watford'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'hammersmith-and-fulham',
    name: 'Hammersmith & Fulham',
    councilType: 'inner-london-borough',
    councilTypeLabel: 'Inner London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Hammersmith', 'Fulham', 'Shepherds Bush', 'White City', 'Brook Green'],
    notes: 'Borders Ealing and Hounslow, with strong schools and local authority commissioning activity.',
    borderingSlugs: ['ealing', 'hounslow', 'kensington-and-chelsea', 'richmond-upon-thames'],
    focusKeyword: 'chaperone services Hammersmith and Fulham',
    metaTitle: 'Chaperone services Hammersmith & Fulham | Child transport West London',
    metaDescription:
      'Chaperone services in Hammersmith and Fulham: Fulham, Shepherds Bush and White City. Child transport and mentoring for schools and local authorities near Ealing and Hounslow.',
    heroDescription:
      'Chaperone services and child transport across Hammersmith and Fulham, with quick access from our Greenford HQ.',
    paragraphs: [
      'Hammersmith and Fulham sits between our Greenford base and central West London schools. CAMS services supports commissioners who need chaperone service cover for contact transport, SEMH school runs and mentoring when placements border Ealing or Hounslow.',
      'Fulham and Shepherds Bush referrals often involve tight scheduling around bridges, event traffic and school gates. We plan routes with realistic buffers and clear handover instructions.',
      'Share postcodes for Brook Green, White City or Hammersmith town centre when you refer so we can confirm practitioner availability from West London.',
    ],
    faq: areaFaq('Hammersmith and Fulham', 'Fulham'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'richmond-upon-thames',
    name: 'Richmond upon Thames',
    councilType: 'inner-london-borough',
    councilTypeLabel: 'Inner London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Richmond', 'Twickenham', 'Teddington', 'Hampton', 'Barnes'],
    notes: 'Borders Hounslow, with high foster and SEND placement volume across South West London.',
    borderingSlugs: ['hounslow', 'hammersmith-and-fulham', 'kensington-and-chelsea'],
    focusKeyword: 'chaperone services Richmond upon Thames',
    metaTitle: 'Chaperone services Richmond | Child transport Twickenham & Teddington',
    metaDescription:
      'Chaperone services in Richmond upon Thames: Twickenham, Teddington, Hampton and Barnes. SEND transport, foster moves and contact centre cover from CAMS services.',
    heroDescription:
      'Chaperone services and school transport across Richmond, Twickenham, Teddington and Hampton.',
    paragraphs: [
      'Richmond upon Thames has a high volume of foster, SEND and family court work. CAMS services provides chaperone services and child transport that respect neutral handovers, PEP priorities and tight contact centre windows.',
      'Twickenham and Teddington routes often cross into Hounslow or Barnes. Tell us when journeys span borough lines so timing and practitioner briefing stay aligned.',
      'We match trauma-informed practitioners for SEMH school transport and for young people who need the same adult across multiple weekly journeys.',
    ],
    faq: areaFaq('Richmond upon Thames', 'Twickenham'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'kensington-and-chelsea',
    name: 'Kensington & Chelsea',
    councilType: 'inner-london-borough',
    councilTypeLabel: 'Inner London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Kensington', 'Chelsea', 'Notting Hill', 'Earls Court', "World's End"],
    notes: 'Adjacent to Hammersmith and Fulham and Richmond, with active local authority commissioning.',
    borderingSlugs: ['hammersmith-and-fulham', 'richmond-upon-thames'],
    focusKeyword: 'chaperone services Kensington and Chelsea',
    metaTitle: 'Chaperone services Kensington & Chelsea | Child transport West London',
    metaDescription:
      'Chaperone services in Kensington and Chelsea for schools, IFAs and local authorities. Contact centre transport, school runs and mentoring from CAMS services.',
    heroDescription:
      'Chaperone services and mentoring in Kensington and Chelsea, commissioned with safeguarding-first standards.',
    paragraphs: [
      'Kensington and Chelsea commissioners often need discreet, reliable chaperone service cover for supervised contact, school attendance and placement stability. CAMS services plans each journey around the young person’s plan and authorised recipients.',
      'Notting Hill, Earls Court and Chelsea present varied traffic and parking constraints. We risk-assess routes in advance and keep referrers informed with factual journey notes where commissioned.',
      'Cases may link to placements in neighbouring Hammersmith and Fulham or Richmond. Include court orders and contact schedules at referral.',
    ],
    faq: areaFaq('Kensington and Chelsea', 'Kensington'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'enfield',
    name: 'Enfield',
    councilType: 'outer-london-borough',
    councilTypeLabel: 'Outer London Borough',
    region: 'Greater London',
    regionSlug: 'greater-london',
    keyAreas: ['Enfield Town', 'Edmonton', 'Southgate', 'Palmers Green', 'Winchmore Hill'],
    notes: 'Borders Barnet, with a large SEND population and strong demand for school transport support.',
    borderingSlugs: ['barnet', 'hertsmere'],
    focusKeyword: 'chaperone services Enfield',
    metaTitle: 'Chaperone services Enfield | Child transport Edmonton & Southgate',
    metaDescription:
      'Chaperone services in Enfield: Edmonton, Southgate, Palmers Green and Enfield Town. SEND school transport and mentoring for North London referrers.',
    heroDescription:
      'Chaperone services, school transport and mentoring across Enfield, Edmonton and Southgate.',
    paragraphs: [
      'Enfield’s SEND population drives demand for consistent school transport and mentoring when mainstream routes are not enough. CAMS services provides chaperone service hours that align with EHCP outcomes and referrer reviews.',
      'Edmonton and Southgate placements may sit next to Barnet schools or Hertfordshire edges. Share full addresses and bell times so we can plan cross-border journeys realistically.',
      'We document factual progress for professionals where commissioned and escalate safeguarding concerns through agreed routes.',
    ],
    faq: areaFaq('Enfield', 'Edmonton'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'hertsmere',
    name: 'Hertsmere',
    councilType: 'county-town',
    councilTypeLabel: 'Hertfordshire (district)',
    region: 'Hertfordshire',
    regionSlug: 'hertfordshire',
    keyAreas: ['Borehamwood', 'Bushey', 'Radlett', 'Potters Bar', 'Elstree'],
    notes: 'Borders Barnet and Watford, extending Hertfordshire cover beyond Watford town.',
    borderingSlugs: ['barnet', 'enfield', 'watford'],
    focusKeyword: 'chaperone services Hertsmere',
    metaTitle: 'Chaperone services Hertsmere | Child transport Borehamwood & Bushey',
    metaDescription:
      'Chaperone services in Hertsmere: Borehamwood, Bushey, Radlett and Potters Bar. Child transport linked to Barnet and Watford placements.',
    heroDescription:
      'Chaperone services and child transport in Hertsmere, from Borehamwood and Bushey to Radlett and Potters Bar.',
    paragraphs: [
      'Hertsmere sits between Barnet and Watford, making it a natural extension of our West London and Hertfordshire routes. CAMS services supports chaperone services for school transport, contact journeys and foster moves when placements cross county lines.',
      'Borehamwood and Bushey referrers often need practitioners who can reach both Hertfordshire schools and North London contact centres. Include termination postcodes in your referral.',
      'Our Greenford HQ gives short access to Potters Bar corridor work. We confirm capacity within one working day.',
    ],
    faq: areaFaq('Hertsmere', 'Borehamwood'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
  {
    slug: 'slough',
    name: 'Slough',
    councilType: 'unitary-borough',
    councilTypeLabel: 'Berkshire (unitary authority)',
    region: 'Berkshire',
    regionSlug: 'berkshire',
    keyAreas: ['Slough', 'Colnbrook', 'Langley', 'Cippenham', 'Wexham'],
    notes: 'Borders Hillingdon, common for Heathrow-adjacent placements and cross-border school transport.',
    borderingSlugs: ['hillingdon', 'ealing'],
    focusKeyword: 'chaperone services Slough',
    metaTitle: 'Chaperone services Slough | Child transport Berkshire & Heathrow corridor',
    metaDescription:
      'Chaperone services in Slough and Berkshire. Child transport for Heathrow-adjacent placements, schools and agencies linked to Hillingdon and West London.',
    heroDescription:
      'Chaperone services and child transport in Slough, Langley and Colnbrook, with links to Hillingdon and West London.',
    paragraphs: [
      'Slough is a unitary authority bordering Hillingdon, with many placements tied to Heathrow corridor travel. CAMS services plans chaperone and child transport with buffer time for motorway delays and strict handover protocols.',
      'Langley and Colnbrook referrals often connect to West London schools or contact centres. Tell us when journeys start or end in Hillingdon or Ealing so we can align practitioners and timing.',
      'We serve Berkshire cases where commissioners want the same safeguarding standards as our London delivery, routed from our Greenford operations base.',
    ],
    faq: areaFaq('Slough', 'Langley'),
    serviceSlugs: CORE_SERVICE_SLUGS,
  },
];
