<?php

use App\Domain\Notifications\IntentType;

return [
    /*
    |--------------------------------------------------------------------------
    | Centralised notification system
    |--------------------------------------------------------------------------
    | intent_types: for each intent, which channels to use (in_app, email, whatsapp).
    | notification_class: Laravel Notification class for email channel (keyed by intent).
    | user_notification_type: UserNotification::TYPE_* for in_app bell (keyed by intent).
    | rate_limits: max notifications per user per channel per day (0 = no limit).
    */

    'channels_per_intent' => [
        IntentType::BOOKING_CONFIRMED => ['in_app', 'email'],
        IntentType::BOOKING_CANCELLED => ['in_app', 'email'],
        IntentType::PAYMENT_CONFIRMED => ['in_app', 'email'],
        IntentType::PAYMENT_FAILED => ['in_app', 'email'],
        IntentType::ACTIVITY_CONFIRMED => ['in_app', 'email'],
        IntentType::SESSION_CANCELLED => ['in_app', 'email'],
        IntentType::SESSION_TODAY => ['in_app', 'email'],
        IntentType::SESSION_OVER => ['in_app', 'email'],
        IntentType::SESSION_STARTED => ['in_app', 'email'],
        IntentType::SESSION_STARTED_ADMIN => ['in_app', 'email'],
        IntentType::SESSION_ENDING_SOON_PARENT => ['in_app', 'email'],
        IntentType::SESSION_ENDING_SOON_ADMIN => ['in_app', 'email'],
        IntentType::SESSION_REMINDER_24H => ['email'],
        IntentType::TRAINER_ASSIGNED => ['in_app', 'email'],
        IntentType::DRAFT_BOOKING_REMINDER_30M => ['email'],
        IntentType::DRAFT_BOOKING_REMINDER_2H => ['email'],
        IntentType::DRAFT_BOOKING_REMINDER_24H => ['email'],
        IntentType::DRAFT_BOOKING_REMINDER_72H => ['email'],
        IntentType::PAYMENT_REMINDER_24H_BEFORE => ['email'],
        IntentType::PAYMENT_REMINDER_3D_BEFORE => ['email'],
        IntentType::PAYMENT_REMINDER_7D_AFTER => ['email'],
        IntentType::CHILD_APPROVED => ['in_app', 'email'],
        IntentType::CHILD_REJECTED => ['in_app', 'email'],
        IntentType::CHILD_CHECKLIST_SUBMITTED => ['in_app', 'email'],
        IntentType::CHILD_CHECKLIST_REMINDER => ['email'],
        IntentType::USER_APPROVED => ['in_app', 'email'],
        IntentType::USER_REJECTED => ['in_app', 'email'],
        IntentType::SESSION_BOOKED => ['in_app', 'email'],
        IntentType::SESSION_CONFIRMATION_REQUEST => ['in_app', 'email'],
        IntentType::SESSION_CANCELLED_TRAINER => ['in_app', 'email'],
        IntentType::TRAINER_FORGOT_CLOCK_OUT => ['in_app', 'email'],
        IntentType::TRAINER_SESSION_ENDING_SOON => ['in_app', 'email'],
        IntentType::TRAINER_SESSION_STARTING_SOON => ['in_app', 'email'],
        IntentType::APPLICATION_APPROVED => ['in_app', 'email'],
        IntentType::APPLICATION_REJECTED => ['in_app', 'email'],
        IntentType::APPLICATION_INFO_REQUESTED => ['in_app', 'email'],
        IntentType::NEW_BOOKING => ['in_app', 'email'],
        IntentType::PAYMENT_RECEIVED => ['in_app', 'email'],
        IntentType::CHILD_APPROVAL_REQUIRED => ['in_app', 'email'],
        IntentType::SESSION_NEEDS_TRAINER => ['in_app', 'email'],
        IntentType::SESSION_BOOKED_ADMIN => ['email'],
        IntentType::TRAINER_APPLICATION_SUBMITTED => ['in_app', 'email'],
        IntentType::ABSENCE_REQUEST_SUBMITTED => ['in_app'],
        IntentType::TRAINER_AVAILABILITY_UPDATED => ['in_app'],
        IntentType::CONTACT_SUBMISSION => ['email', 'whatsapp'],
        IntentType::CHILD_CHECKLIST_SUBMITTED_ADMIN => ['in_app', 'email'],
    ],

    'intent_to_mailable_class' => [
        IntentType::CHILD_APPROVED => \App\Mail\ChildApprovedNotification::class,
        IntentType::CHILD_REJECTED => \App\Mail\ChildRejectedNotification::class,
        IntentType::USER_APPROVED => \App\Mail\UserApprovedNotification::class,
        IntentType::USER_REJECTED => \App\Mail\UserRejectedNotification::class,
    ],

    'intent_to_notification_class' => [
        IntentType::BOOKING_CONFIRMED => \App\Notifications\BookingConfirmationNotification::class,
        IntentType::BOOKING_CANCELLED => \App\Notifications\BookingCancellationNotification::class,
        IntentType::PAYMENT_CONFIRMED => \App\Notifications\PaymentConfirmationNotification::class,
        IntentType::PAYMENT_FAILED => \App\Notifications\PaymentFailedNotification::class,
        IntentType::ACTIVITY_CONFIRMED => \App\Notifications\ActivityConfirmationNotification::class,
        IntentType::SESSION_TODAY => \App\Notifications\SessionTodayNotification::class,
        IntentType::SESSION_OVER => \App\Notifications\ParentSessionOverNotification::class,
        IntentType::SESSION_STARTED => \App\Notifications\ParentSessionStartedNotification::class,
        IntentType::SESSION_STARTED_ADMIN => \App\Notifications\AdminSessionStartedNotification::class,
        IntentType::SESSION_ENDING_SOON_PARENT => \App\Notifications\ParentSessionEndingSoonNotification::class,
        IntentType::SESSION_ENDING_SOON_ADMIN => \App\Notifications\AdminSessionEndingSoonNotification::class,
        IntentType::SESSION_REMINDER_24H => \App\Notifications\SessionReminder24HoursNotification::class,
        IntentType::TRAINER_ASSIGNED => \App\Notifications\ParentTrainerAssignedNotification::class,
        IntentType::DRAFT_BOOKING_REMINDER_30M => \App\Notifications\DraftBookingReminder30MinutesNotification::class,
        IntentType::DRAFT_BOOKING_REMINDER_2H => \App\Notifications\DraftBookingReminder2HoursNotification::class,
        IntentType::DRAFT_BOOKING_REMINDER_24H => \App\Notifications\DraftBookingReminder24HoursNotification::class,
        IntentType::DRAFT_BOOKING_REMINDER_72H => \App\Notifications\DraftBookingReminder72HoursNotification::class,
        IntentType::PAYMENT_REMINDER_24H_BEFORE => \App\Notifications\PaymentReminder24HoursNotification::class,
        IntentType::PAYMENT_REMINDER_3D_BEFORE => \App\Notifications\PaymentReminder3DaysNotification::class,
        IntentType::PAYMENT_REMINDER_7D_AFTER => \App\Notifications\PaymentReminderFinalNotification::class,
        IntentType::CHILD_CHECKLIST_REMINDER => \App\Notifications\ChildChecklistReminderNotification::class,
        IntentType::SESSION_BOOKED => \App\Notifications\TrainerSessionBookedNotification::class,
        IntentType::SESSION_CONFIRMATION_REQUEST => \App\Notifications\TrainerSessionConfirmationRequestNotification::class,
        IntentType::SESSION_CANCELLED_TRAINER => \App\Notifications\TrainerSessionCancelledNotification::class,
        IntentType::TRAINER_FORGOT_CLOCK_OUT => \App\Notifications\TrainerForgotClockOutNotification::class,
        IntentType::TRAINER_SESSION_ENDING_SOON => \App\Notifications\TrainerSessionEndingSoonNotification::class,
        IntentType::TRAINER_SESSION_STARTING_SOON => \App\Notifications\TrainerSessionStartingSoonNotification::class,
        IntentType::NEW_BOOKING => \App\Notifications\AdminNewBookingNotification::class,
        IntentType::PAYMENT_RECEIVED => \App\Notifications\AdminPaymentReceivedNotification::class,
        IntentType::CHILD_APPROVAL_REQUIRED => \App\Notifications\AdminChildApprovalRequiredNotification::class,
        IntentType::SESSION_NEEDS_TRAINER => \App\Notifications\AdminSessionNeedsTrainerNotification::class,
        IntentType::SESSION_BOOKED_ADMIN => \App\Notifications\AdminSessionBookedNotification::class,
        IntentType::TRAINER_APPLICATION_SUBMITTED => \App\Notifications\AdminTrainerApplicationSubmittedNotification::class,
        IntentType::CONTACT_SUBMISSION => \App\Notifications\NewContactSubmissionNotification::class,
        IntentType::CHILD_CHECKLIST_SUBMITTED_ADMIN => \App\Notifications\AdminChildChecklistSubmittedNotification::class,
    ],

    'intent_to_user_notification_type' => [
        IntentType::BOOKING_CONFIRMED => \App\Models\UserNotification::TYPE_BOOKING_CONFIRMED,
        IntentType::BOOKING_CANCELLED => \App\Models\UserNotification::TYPE_BOOKING_CANCELLED,
        IntentType::PAYMENT_CONFIRMED => \App\Models\UserNotification::TYPE_PAYMENT_CONFIRMED,
        IntentType::PAYMENT_FAILED => \App\Models\UserNotification::TYPE_PAYMENT_FAILED,
        IntentType::ACTIVITY_CONFIRMED => \App\Models\UserNotification::TYPE_ACTIVITY_CONFIRMED,
        IntentType::SESSION_CANCELLED => \App\Models\UserNotification::TYPE_SESSION_CANCELLED,
        IntentType::SESSION_TODAY => \App\Models\UserNotification::TYPE_SESSION_TODAY,
        IntentType::SESSION_OVER => \App\Models\UserNotification::TYPE_SESSION_OVER,
        IntentType::SESSION_STARTED => \App\Models\UserNotification::TYPE_SESSION_STARTED,
        IntentType::SESSION_STARTED_ADMIN => \App\Models\UserNotification::TYPE_SESSION_STARTED_ADMIN,
        IntentType::SESSION_ENDING_SOON_PARENT => \App\Models\UserNotification::TYPE_SESSION_ENDING_SOON_PARENT,
        IntentType::SESSION_ENDING_SOON_ADMIN => \App\Models\UserNotification::TYPE_SESSION_ENDING_SOON_ADMIN,
        IntentType::TRAINER_ASSIGNED => \App\Models\UserNotification::TYPE_TRAINER_ASSIGNED,
        IntentType::CHILD_APPROVED => \App\Models\UserNotification::TYPE_CHILD_APPROVED,
        IntentType::CHILD_REJECTED => \App\Models\UserNotification::TYPE_CHILD_REJECTED,
        IntentType::CHILD_CHECKLIST_SUBMITTED => \App\Models\UserNotification::TYPE_CHILD_CHECKLIST_SUBMITTED,
        IntentType::USER_APPROVED => \App\Models\UserNotification::TYPE_USER_APPROVED,
        IntentType::USER_REJECTED => \App\Models\UserNotification::TYPE_USER_REJECTED,
        IntentType::SESSION_BOOKED => \App\Models\UserNotification::TYPE_SESSION_BOOKED,
        IntentType::SESSION_CONFIRMATION_REQUEST => \App\Models\UserNotification::TYPE_SESSION_BOOKED,
        IntentType::SESSION_CANCELLED_TRAINER => \App\Models\UserNotification::TYPE_SESSION_CANCELLED_TRAINER,
        IntentType::TRAINER_FORGOT_CLOCK_OUT => \App\Models\UserNotification::TYPE_TRAINER_FORGOT_CLOCK_OUT,
        IntentType::TRAINER_SESSION_ENDING_SOON => \App\Models\UserNotification::TYPE_TRAINER_SESSION_ENDING_SOON,
        IntentType::TRAINER_SESSION_STARTING_SOON => \App\Models\UserNotification::TYPE_TRAINER_SESSION_STARTING_SOON,
        IntentType::APPLICATION_APPROVED => \App\Models\UserNotification::TYPE_APPLICATION_APPROVED,
        IntentType::APPLICATION_REJECTED => \App\Models\UserNotification::TYPE_APPLICATION_REJECTED,
        IntentType::APPLICATION_INFO_REQUESTED => \App\Models\UserNotification::TYPE_APPLICATION_INFO_REQUESTED,
        IntentType::NEW_BOOKING => \App\Models\UserNotification::TYPE_NEW_BOOKING,
        IntentType::PAYMENT_RECEIVED => \App\Models\UserNotification::TYPE_PAYMENT_RECEIVED,
        IntentType::CHILD_APPROVAL_REQUIRED => \App\Models\UserNotification::TYPE_CHILD_APPROVAL_REQUIRED,
        IntentType::SESSION_NEEDS_TRAINER => \App\Models\UserNotification::TYPE_SESSION_NEEDS_TRAINER,
        IntentType::TRAINER_APPLICATION_SUBMITTED => \App\Models\UserNotification::TYPE_TRAINER_APPLICATION_SUBMITTED,
        IntentType::ABSENCE_REQUEST_SUBMITTED => \App\Models\UserNotification::TYPE_ABSENCE_REQUEST_SUBMITTED,
        IntentType::TRAINER_AVAILABILITY_UPDATED => \App\Models\UserNotification::TYPE_TRAINER_AVAILABILITY_UPDATED,
        IntentType::CHILD_CHECKLIST_SUBMITTED_ADMIN => \App\Models\UserNotification::TYPE_CHILD_CHECKLIST_SUBMITTED_ADMIN,
    ],

    'rate_limits' => [
        'email' => (int) env('NOTIFICATION_RATE_LIMIT_EMAIL_PER_DAY', 20),
        'in_app' => (int) env('NOTIFICATION_RATE_LIMIT_IN_APP_PER_DAY', 50),
        'whatsapp' => (int) env('NOTIFICATION_RATE_LIMIT_WHATSAPP_PER_DAY', 10),
    ],

    'queue' => env('NOTIFICATION_QUEUE', 'default'),
    'dedupe_ttl_minutes_fallback' => 60,

    /*
    | Entity type to Eloquent model (for loading subject in queued jobs).
    */
    'entity_model' => [
        'booking' => \App\Models\Booking::class,
        'schedule' => \App\Models\BookingSchedule::class,
        'child' => \App\Models\Child::class,
        'user' => \App\Models\User::class,
        'contact_submission' => \App\Models\ContactSubmission::class,
        'trainer_application' => \App\Models\TrainerApplication::class,
    ],
];
