#!/usr/bin/env node
/**
 * FAANG-Level Frontend Validation Script
 * Validates frontend environment before development
 */

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const NEXT_ENV_FILE = path.join(PROJECT_ROOT, 'next-env.d.ts');

let errors = 0;
let warnings = 0;

function error(msg) {
    console.error(`❌ ${msg}`);
    errors++;
}

function warning(msg) {
    console.warn(`⚠️  ${msg}`);
    warnings++;
}

function success(msg) {
    console.log(`✓ ${msg}`);
}

console.log('🔍 Validating frontend environment...\n');

// Check 1: next-env.d.ts should not be in Git
if (fs.existsSync(NEXT_ENV_FILE)) {
    try {
        const { execSync } = require('child_process');
        try {
            execSync(`git ls-files --error-unmatch ${NEXT_ENV_FILE}`, {
                stdio: 'ignore',
                cwd: PROJECT_ROOT
            });
            error('next-env.d.ts is tracked in Git (should be ignored)');
        } catch (e) {
            success('next-env.d.ts is properly ignored');
        }
    } catch (e) {
        // Git not available - skip
    }
} else {
    success('next-env.d.ts does not exist (will be generated by Next.js)');
}

// Check 2: .gitignore includes next-env.d.ts
const gitignorePath = path.join(PROJECT_ROOT, '..', '.gitignore');
if (fs.existsSync(gitignorePath)) {
    const gitignore = fs.readFileSync(gitignorePath, 'utf8');
    if (gitignore.includes('next-env.d.ts')) {
        success('next-env.d.ts is in .gitignore');
    } else {
        warning('next-env.d.ts is not in .gitignore');
    }
}

// Check 3: TypeScript config exists
const tsconfigPath = path.join(PROJECT_ROOT, 'tsconfig.json');
if (fs.existsSync(tsconfigPath)) {
    success('tsconfig.json exists');
} else {
    error('tsconfig.json is missing');
}

// Summary
console.log('\n');
if (errors === 0 && warnings === 0) {
    console.log('✓ All checks passed!');
    process.exit(0);
} else if (errors === 0) {
    console.log(`⚠️  Validation passed with ${warnings} warning(s)`);
    process.exit(0);
} else {
    console.log(`❌ Validation failed with ${errors} error(s) and ${warnings} warning(s)`);
    process.exit(1);
}

