/**
 * Contact page UI strings and config.
 * Never hardcode these in JSX — use these constants or config from CMS.
 */

export const CONTACT_HERO = {
  TITLE: "Transform Your Child's Future Today.",
  SUBTITLE: 'Book a FREE consultation and discover how our trauma-informed care can help your child thrive.',
  CTA_PRIMARY: 'Get Your FREE Consultation',
  CTA_CALL: 'Or Call Now',
  CTA_NUMBER_COMING_SOON: 'Or Call Now',
} as const;

export const CONTACT_STATS = [
  { value: '500+', label: 'Happy families' },
  { value: '10+', label: 'Years experience' },
  { value: '98%', label: 'Satisfaction' },
  { value: '24h', label: 'Response time' },
] as const;

export const CONTACT_FORM = {
  TITLE: 'Book Your FREE Consultation.',
  SUBTITLE: "Take a free consultation and we'll get back to you within 24-hours to discuss how we can help your child thrive.",
  LABEL_FIRST_NAME: 'Your Name *',
  LABEL_LAST_NAME: 'Your Last Name *',
  LABEL_EMAIL: 'Your Email *',
  LABEL_PHONE: 'Your Phone *',
  LABEL_CHILD_NAME: "Your Child's Name *",
  LABEL_CHILD_AGE: "Your Child's Age *",
  LABEL_CHILDREN: 'Children *',
  ADD_ANOTHER_CHILD: 'Add Another Child',
  CHILD_N: 'Child',
  REMOVE: 'Remove',
  LABEL_FULL_NAME: 'Full Name *',
  LABEL_AGE: 'Age *',
  LABEL_ADDRESS: 'Address Line 1 *',
  LABEL_ADDRESS_LINE_2: 'Address Line 2 (Optional)',
  LABEL_POSTAL_CODE: 'Postcode *',
  LABEL_HEAR_ABOUT: 'How did you hear about us?',
  LABEL_SUPPORT: 'What might we be able to support?',
  LABEL_INTERESTED_IN: "I'm Interested In *",
  LABEL_URGENCY: 'When do you need support? *',
  LABEL_PREFERRED_CONTACT: 'Best way to reach you? *',
  LABEL_MESSAGE: 'Tell us about your needs (Optional)',
  CHECKBOX_MARKETING: 'I am happy to receive marketing information',
  CHECKBOX_TERMS: 'I agree to the Terms & Conditions and Privacy Policy *',
  PLACEHOLDER_FIRST_NAME: 'First name',
  PLACEHOLDER_LAST_NAME: 'Last name',
  PLACEHOLDER_NAME: 'John Smith',
  PLACEHOLDER_EMAIL: 'john@example.com',
  PLACEHOLDER_PHONE: '07123 456789 or 020 1234 5678',
  PLACEHOLDER_ADDRESS: 'e.g., 123 High Street, Town',
  PLACEHOLDER_POSTCODE: 'e.g., IG9 5BT',
  PLACEHOLDER_AGE: 'e.g., 8',
  PLACEHOLDER_MESSAGE: 'Tell us how we can help...',
  SELECT_SERVICE_OR_PACKAGE: 'Select a service or package...',
  SELECT_HEAR_ABOUT: 'Select...',
  HEAR_ABOUT_OPTIONS: ['Search engine', 'Social media', 'Friend or family', 'School or referral', 'Other'] as const,
  OPTGROUP_PACKAGES: 'Popular Packages',
  OPTGROUP_SERVICES: 'Individual Services',
  OPTION_GENERAL: 'Just have a question',
  SELECT_TIMEFRAME: 'Select timeframe...',
  URGENCY_URGENT: 'Urgent - Within a week',
  URGENCY_SOON: 'Soon - Within 2-4 weeks',
  URGENCY_EXPLORING: 'Just exploring options',
  PREFERRED_EMAIL: 'Email',
  PREFERRED_PHONE: 'Phone',
  PREFERRED_WHATSAPP: 'WhatsApp',
  SUBMIT: 'Confirm My FREE Consultation',
  SENDING: 'Sending...',
  SECURITY_NOTE: 'Your information is 100% secure. We respect your privacy and never share your data.',
  ERROR_SELECT_OPTION: 'Please select an option',
  ERROR_SELECT_TIMEFRAME: 'Please select a timeframe',
  ERROR_TERMS_REQUIRED: 'You must agree to the Terms & Conditions and Privacy Policy',
  SUCCESS_MESSAGE: 'Thank you! Your message has been sent successfully.',
  ERROR_GENERIC: 'Something went wrong. Please try again or contact us directly.',
  ERROR_WAIT: 'Please wait a few moments before trying again. This helps prevent duplicate submissions.',
  ERROR_ALTERNATIVE: 'You can also reach us by phone at',
  ERROR_ALTERNATIVE_SUFFIX: 'or WhatsApp for immediate assistance.',
} as const;

export const CONTACT_SIDEBAR = {
  WHY_TITLE: 'Why Families Choose Us.',
  BENEFITS: [
    'Free no-obligation 15-min call',
    'Trained trauma-informed teachers',
    'High quality learning materials',
    'Regular progress updates & reports',
    'Fun and interactive activities',
  ] as const,
  PREFER_TALK_TITLE: 'Prefer to Talk Now?',
  PREFER_TALK_DESCRIPTION: "We're here to help! Choose your preferred contact method:",
  PREFER_CALL_NOW: 'Call Now',
  PREFER_SEND_MESSAGE: 'Send us a message',
  PREFER_BOOK_CALL: 'Book a call',
  CALL_US: 'Call us',
  WHATSAPP: 'WhatsApp',
  EMAIL_US: 'Email Us',
  OFFICE_HOURS_TITLE: 'Office Hours.',
  MONDAY_FRIDAY: 'Monday - Friday',
  MONDAY_FRIDAY_HOURS: '9 AM - 5 PM',
  SATURDAY: 'Saturday',
  SATURDAY_HOURS: '9 AM - 1 PM',
  SUNDAY: 'Sunday',
  SUNDAY_HOURS: 'Closed',
  AFTER_HOURS: "After hours? Feel free to email us and we'll reply to your query.",
} as const;

export const CONTACT_VISIT = {
  TITLE: 'Visit Our Centre',
  SUBTITLE: "Located in the heart of Buckhurst Hill, we're easily accessible and offer a welcoming, safe environment for all families.",
  MAP_COMING_SOON: 'Map coming soon',
  MAP_TITLE: 'Location of CAMS Services',
  ADDRESS_LABEL: 'Our Address',
  ADDRESS_COMING_SOON: 'Address coming soon',
  ADDRESS_PLACEHOLDER: 'Buckhurst Hill, England',
  GET_DIRECTIONS: 'Get Directions →',
  GET_DIRECTIONS_HREF: 'https://maps.google.com',
  PARKING_LABEL: 'Parking & Access',
  PARKING_DESCRIPTION: 'Free parking available. Wheelchair accessible. Close to public transport.',
  BOOK_VISIT_LABEL: 'Book a Visit',
  BOOK_VISIT_DESCRIPTION: 'Want to see our facilities? Schedule a tour of our centre!',
  SCHEDULE_TOUR: 'Schedule Tour',
} as const;

export const CONTACT_CTA = {
  TITLE: 'Ready to Take the First Step?',
  SUBTITLE: "Join hundreds of families who trust us with their children's development.",
  CTA_PRIMARY: "Get Started - It's FREE!",
  CTA_CALL: 'Or Call Us Now',
  PHONE_COMING_SOON: 'Phone coming soon',
  FOOTER: '100% satisfaction guaranteed · No long-term commitment · Cancel anytime',
} as const;

export const CONTACT_VALIDATION_FALLBACKS = {
  NAME: 'Please enter both first and last name',
  EMAIL: 'Please enter a valid email address',
  PHONE: 'Please enter a valid UK phone number',
  ADDRESS_REQUIRED: 'Address is required',
  ADDRESS_INVALID: 'Address must start with a door number',
  POSTCODE_REQUIRED: 'Postal code is required',
  POSTCODE_INVALID: 'Please enter a valid UK postal code',
  AGE: 'Please enter a valid age (0-25)',
  PASSWORD: 'Password is invalid',
} as const;
