import type { PractitionerProfile } from '@/marketing/content/practitioners/types';

export const KENNETH_HOLDER_PROFILE: PractitionerProfile = {
  slug: 'kenneth-holder',
  name: 'Kenneth Holder',
  role: 'Founder and Director',
  company: 'CAMS Services Ltd',
  avatarKey: 'kenneth-holder',
  metaTitle: 'Kenneth Holder | Founder & Director | CAMS Services Ltd',
  metaDescription:
    'Meet Kenneth Holder, Founder and Director of CAMS Services Ltd. DBS-checked mentoring, chaperone services and child transport. Enquire through CAMS Services only.',
  heroEyebrow: 'Practitioner profile',
  heroSubtitle:
    'Founder and Director of CAMS Services Ltd. One-to-one mentoring, chaperone services and safeguarding-led child transport for families, schools and commissioners.',
  aboutParagraphs: [
    "Hello, I'm Kenneth, Founder and Director of CAMS Services.",
    'Working with children and young people is not simply my career. It is something I genuinely enjoy and take pride in.',
    'Over the past 10+ years, I have supported children, young people and families across education, community settings and family support services. Throughout that time I have worked with children from many different backgrounds, including those with SEND, children in care, young people experiencing emotional or behavioural challenges and those needing positive role models and consistent support.',
    'My approach is simple. I believe you connect before you correct.',
    "Children respond when they feel listened to, respected and understood. Taking time to understand a young person's interests, personality, worries and strengths allows trust to grow naturally. Once trust has been built, meaningful progress becomes much more achievable.",
    'I aim to be someone young people enjoy spending time with while still providing clear boundaries, positive guidance and encouragement.',
    'As a father myself, and someone who grew up in care, I understand the importance of having adults who are patient, dependable and genuinely invested in helping children succeed. My own experiences have given me insight into the importance of stability, positive relationships and creating opportunities for young people to enjoy life and build confidence.',
    'I bring enthusiasm, energy and creativity into every session. If one activity is not working, I adapt. If a young person is struggling to engage, I look for another approach. Every child is different, so every session should feel personal.',
    "I enjoy finding activities that match each young person's personality rather than expecting every child to fit into the same programme.",
  ],
  experienceIntro: 'Over six years supporting children and young people directly, alongside more than a decade in the wider sector.',
  experienceItems: [
    'One to one mentoring',
    'SEND support',
    'Community access support',
    'Chaperone services',
    'Family contact centre work',
    'Appropriate Adult services',
    'Primary schools',
    'Secondary schools',
    'Faith schools',
    'Alternative education settings',
    "Residential children's homes",
    'Working alongside parents, carers, schools and professionals',
    'Supporting young people with confidence, independence and emotional wellbeing',
    'Safeguarding-led child transport between homes, schools and contact centres',
  ],
  approachIntro: 'I believe every child deserves someone who:',
  approachItems: [
    'Listens without judgement',
    'Builds trust before expecting change',
    'Is patient and consistent',
    'Encourages confidence',
    'Promotes independence',
    'Creates enjoyable experiences',
    'Keeps children safe',
    'Celebrates small achievements',
    'Supports education and personal development',
    'Understands that progress looks different for every child',
  ],
  qualificationsIntro:
    'Kenneth continues to complete professional training to maintain high standards of safeguarding and practice.',
  qualifications: [
    'Enhanced DBS',
    'Safeguarding Children',
    'First Aid',
    'Prevent Duty',
    'Health and Safety',
    'Equality and Diversity',
    'Lone Working',
    'Behaviour Management',
    'SEND awareness',
    'Risk Assessment',
    'GDPR and Confidentiality',
    'Public Liability Insurance',
    'Full UK Driving Licence',
  ],
  interestsIntro: 'Building positive relationships often starts with shared interests.',
  interests: [
    'Swimming',
    'Football',
    'Badminton',
    'Paddle sports',
    'Kayaking',
    'Cycling',
    'Trampolining',
    'Go Karting',
    'Nature walks',
    'Adventure parks',
    'Mini golf',
    'Bowling',
    'Escape rooms',
    'Museums',
    'Aquariums',
    'Wildlife parks',
    'Theme parks',
    'Parks and outdoor games',
    'Photography',
    'Exploring new places',
    'Community events',
  ],
  interestsFooter:
    'I also enjoy keeping up to date with the interests of young people, including current trends, games, social media and popular culture. Understanding what interests them helps build stronger conversations and genuine connections.',
  familiesExpectParagraphs: [
    "When I arrive, I don't simply focus on completing an activity. I focus on building a relationship.",
    "If a young person feels anxious or does not want to engage, I won't give up. I'll adapt, slow things down, find another activity or simply spend time talking until they feel comfortable.",
    'My goal is that every young person finishes a session feeling listened to, respected and looking forward to the next one.',
    'All enquiries and bookings are handled through CAMS Services Ltd. Practitioner personal telephone numbers are not published on this page.',
  ],
  professionalDocumentsIntro:
    'The following documents are available to authorised professionals after secure login. Families and commissioners should contact CAMS Services to request verification.',
  professionalDocuments: [
    'Enhanced DBS Certificate',
    'DBS Update Service Status',
    'Public Liability Insurance',
    'Motor Insurance (Business Use)',
    'Driving Licence Verification',
    'Safeguarding Certificate',
    'First Aid Certificate',
    'Risk Assessments',
    'Lone Working Policy',
    'Safeguarding Policy',
    'Complaints Policy',
    'Behaviour Management Policy',
    'Data Protection Policy',
    'Health and Safety Policy',
    'Equality and Diversity Policy',
    'Professional References',
    'Training Certificates',
    'Practitioner Induction Records',
  ],
  servicesSummary: [
    'One-to-one mentoring',
    'Chaperone services',
    'Supervised child transport',
    'SEND support',
    'Community access',
    'Family contact support',
  ],
  futureFeatures: [
    'Practitioner introduction video',
    'Calendar availability',
    'Languages spoken',
    'Areas covered map',
    'Activity specialisms',
    'SEND experience badges',
    'Reviews from families (subject to consent)',
    'Favourite activities gallery',
    'CPD training timeline',
    'Secure document centre',
  ],
};
