#!/bin/bash
# FAANG-Level Machine-Independent Setup Script
# Ensures consistent environment across Windows, Mac, and Linux
# Run this script after cloning or switching machines

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  FAANG-Level Machine-Independent Setup                  ║${NC}"
echo -e "${BLUE}║  Ensuring consistent environment across all platforms   ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to print step
print_step() {
    echo -e "${GREEN}▶${NC} $1"
}

# Function to print warning
print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# Function to print error
print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Function to print success
print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

# Step 1: Verify Prerequisites
print_step "Verifying prerequisites..."

if ! command_exists docker; then
    print_error "Docker is not installed. Please install Docker Desktop."
    exit 1
fi
print_success "Docker is installed"

if ! command_exists docker-compose && ! docker compose version >/dev/null 2>&1; then
    print_error "Docker Compose is not installed."
    exit 1
fi
print_success "Docker Compose is available"

if ! command_exists git; then
    print_error "Git is not installed."
    exit 1
fi
print_success "Git is installed"

echo ""

# Step 2: Clean Generated Files (Platform-Independent)
print_step "Cleaning auto-generated files..."

cd "$PROJECT_ROOT/frontend"

# Remove next-env.d.ts (will be regenerated by Next.js)
if [ -f "next-env.d.ts" ]; then
    rm -f next-env.d.ts
    print_success "Removed next-env.d.ts (will be regenerated)"
fi

# Remove .next directory (will be regenerated on build)
if [ -d ".next" ]; then
    print_warning ".next directory exists (will be regenerated on build)"
fi

# Remove node_modules if it exists locally (Docker uses volume)
if [ -d "node_modules" ] && [ ! -L "node_modules" ]; then
    print_warning "Local node_modules detected (Docker uses volume mount)"
    print_warning "Consider removing it: rm -rf node_modules"
fi

cd "$PROJECT_ROOT/backend"

# Remove Laravel cache files
if [ -d "bootstrap/cache" ]; then
    find bootstrap/cache -type f ! -name '.gitkeep' -delete 2>/dev/null || true
    print_success "Cleaned Laravel bootstrap cache"
fi

if [ -d "storage/framework/cache" ]; then
    find storage/framework/cache -type f ! -name '.gitkeep' -delete 2>/dev/null || true
    print_success "Cleaned Laravel storage cache"
fi

cd "$PROJECT_ROOT"
echo ""

# Step 3: Verify .gitignore Configuration
print_step "Verifying .gitignore configuration..."

GENERATED_FILES=(
    "frontend/next-env.d.ts"
    "frontend/.next"
    "backend/bootstrap/cache/*"
    "backend/storage/framework/cache/*"
)

for file in "${GENERATED_FILES[@]}"; do
    if git check-ignore -q "$file" 2>/dev/null; then
        print_success "$file is properly ignored"
    else
        print_warning "$file is not in .gitignore (should be ignored)"
    fi
done

echo ""

# Step 4: Check for Committed Generated Files
print_step "Checking for accidentally committed generated files..."

COMMITTED_GENERATED=$(git ls-files | grep -E "(next-env\.d\.ts|\.next/)" || true)

if [ -n "$COMMITTED_GENERATED" ]; then
    print_error "Found committed generated files:"
    echo "$COMMITTED_GENERATED"
    print_warning "These files should not be in Git. Run: git rm --cached <file>"
else
    print_success "No generated files found in Git"
fi

echo ""

# Step 5: Verify Environment Files
print_step "Verifying environment files..."

# Check backend .env
if [ ! -f "backend/.env" ]; then
    print_warning "backend/.env does not exist"
    print_warning "Docker Compose has defaults, but .env is recommended"
    if [ -f "backend/.env.example" ]; then
        print_warning "Copy backend/.env.example to backend/.env and customize"
    fi
else
    print_success "backend/.env exists"
fi

# Check frontend .env.local
if [ ! -f "frontend/.env.local" ]; then
    print_warning "frontend/.env.local does not exist"
    print_warning "Docker Compose has defaults, but .env.local is recommended"
    if [ -f "frontend/env.template" ]; then
        print_warning "Copy frontend/env.template to frontend/.env.local and customize"
    fi
else
    print_success "frontend/.env.local exists"
fi

echo ""

# Step 6: Verify Docker is Running
print_step "Verifying Docker is running..."

if ! docker info >/dev/null 2>&1; then
    print_error "Docker is not running. Please start Docker Desktop."
    exit 1
fi
print_success "Docker is running"

echo ""

# Step 7: Check Port Availability
print_step "Checking port availability..."

PORTS=(4300 9080 33306 9081 36379 11025 18025)
PORT_NAMES=("Frontend" "Backend" "MySQL" "phpMyAdmin" "Redis" "Mailhog SMTP" "Mailhog UI")

for i in "${!PORTS[@]}"; do
    PORT=${PORTS[$i]}
    NAME=${PORT_NAMES[$i]}
    
    if command_exists lsof; then
        # Mac/Linux
        if lsof -Pi :$PORT -sTCP:LISTEN -t >/dev/null 2>&1; then
            print_warning "$NAME port $PORT is in use"
        else
            print_success "$NAME port $PORT is available"
        fi
    elif command_exists netstat; then
        # Windows (Git Bash)
        if netstat -an | grep -q ":$PORT.*LISTEN"; then
            print_warning "$NAME port $PORT is in use"
        else
            print_success "$NAME port $PORT is available"
        fi
    else
        print_warning "Cannot check port $PORT (lsof/netstat not available)"
    fi
done

echo ""

# Step 8: Platform-Specific Fixes
print_step "Applying platform-specific fixes..."

# Detect OS
if [[ "$OSTYPE" == "darwin"* ]]; then
    OS="macOS"
    print_success "Detected macOS"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    OS="Linux"
    print_success "Detected Linux"
elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    OS="Windows"
    print_success "Detected Windows (Git Bash/Cygwin)"
else
    OS="Unknown"
    print_warning "Unknown OS: $OSTYPE"
fi

# macOS-specific: Fix line endings
if [ "$OS" = "macOS" ]; then
    print_success "macOS detected - line endings will be handled by Git"
fi

# Windows-specific: Fix line endings
if [ "$OS" = "Windows" ]; then
    print_success "Windows detected - line endings will be handled by Git"
fi

echo ""

# Step 9: Summary
echo -e "${BLUE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Setup Complete!                                         ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "  1. Review any warnings above"
echo "  2. Create .env files if needed (see warnings)"
echo "  3. Start Docker services: ${BLUE}docker compose up -d${NC}"
echo "  4. Wait for services to be ready"
echo "  5. Access frontend: ${BLUE}http://localhost:4300${NC}"
echo ""
echo -e "${GREEN}For detailed setup instructions, see:${NC}"
echo "  - docs/cleanarchitecture/developer-guide/MACHINE_INDEPENDENT_SETUP.md"
echo "  - docs/cleanarchitecture/developer-guide/NEXT_ENV_DTS_FIX.md"
echo ""

